version: 2

models:
  - name: dim_carmake
    description: "Dimension de marcas de vehiculos. Contiene una clave unica para cada marca"
    columns:
      - name: ID_CARMAKE
        description: "Clase subrogada unica para cada marca de vehiculo"
        tests:
          - unique
          - not_null
      - name: CARMAKE
        description: "Nombre de la marca de vehiculo"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Toyota','Honda', 'Ford', 'Chevolet', 'Nissan', 'BMW', 'Audi', 'Volkswagen', 'Mercedes-Benz']
              config:
                severity: warn

  - name: dim_salesperson
    description: "Dimension de vendedores. Contiene una clave unica para cada vendedor"
    columns:
      - name: ID_SALESPERSON
        description: "Clase subrogada unica para cada vendedor"
        tests:
          - unique
          - not_null
      - name: SALESPERSON
        description: "Nombre del vendedor"
        tests:
          - notnull

  - name: fct_montly_sales  #tabla de hechos
    description: "Tabla de hechos que consolida las ventas mensuales agregadas por vendedor marca de vehiculo, utilizando claves de dimension"
    columns:
      - name: DDATE
        description: "Mes de la venta (primer dia del mes)"
        tests:
          - not_null
      - name: ID_CARMAKE
        description: "Clave foranea a la dimension dim_carmake"
        tests:
          - not_null
          - relationships:    #prueba de integridad referencial
              arguments:
                field: ID_CARMAKE
                to: ID_CARMAKE
                to: ref('dim_carmake')

      - name: ID_SALESPERSON
        description: "Clave foranea a la dimension dim_salesperson"
        tests:
          - not_null
          - relationships:      #prueba de integridad referencial
              arguments:
                field: ID_SALESPERSON
                to: ID_SALESPERSON
                to: ref('dim_salesperson')

      - name: "TOTALSALE"
        description: "Monto total de la venta neta para ese mes, vendedor y marca"
      - name: "TOTALCOM"
        description: "Monto total de la comision para ese mes, vendedor y marca"